spring.application.name=db-management

# PostgreSQL（本番は環境変数必須）
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.init.password=${INIT_PASSWORD}

spring.jpa.open-in-view=false
